// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Client struct {
	ClientID      pgtype.UUID
	AddressClient string
	ClientName    string
	ClientCity    string
	ClientState   string
}

type FuelHistory struct {
	FuelHistoryID  pgtype.UUID
	ClientID       pgtype.UUID
	Gallons        float64
	PricePerGallon float64
	TotalPrice     float64
	DeliveryDate   time.Time
	Timestamp      sql.NullTime
}
